services:
    postgres:
        image: postgres:13
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_DB: schub
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build:
            context: ./back/src
        container_name: backend-app
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/schub
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
        ports:
            - "8080:8080"

    frontend:
        build:
            context: ./
        container_name: frontend-app
        ports:
            - "3000:3000"
        depends_on:
            - backend

volumes:
    postgres_data: